sudo: false
language: node_js
node_js:
  - stable
cache: node_modules
branches:
  only:
    - dev # build dev branch only
script:
  - hexo g # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "ch4o5"
  - git config user.email "li_dongyun@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/Thief-of-DarkShire/Thief-of-DarkShire.github.io.git" master:master
