sudo: false
language: node_js
node_js:
  - stable
cache: node_modules
branches:
  only:
    - dev # build dev branch only
script:
  - hexo g # generate static files
after_script:
  - git config user.name "ch4o5"
  - git config user.email "li_dongyun@outlook.com"
  - hexo d